[brainflow]
git-tree-sha1 = "61fd45fc3b6cc03b85a7feecfd298bedcc484104"
lazy = true

    [[brainflow.download]]
    sha256 = "3f0ec287afec2f8aeaeb4124a129bc45611a4358c37580424fd963cf4aa882e3"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.13.0/compiled_libs.tar"
