[brainflow]
git-tree-sha1 = "fc5e264369ce67547ec776a114da629d3f668454"
lazy = true

    [[brainflow.download]]
    sha256 = "22b36de5909d1edd77f17ddfac111f3f6a41ebd2f7defa935fe5a65ac6bce60f"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.13.3/compiled_libs.tar"
