[brainflow]
git-tree-sha1 = "cfb23a280c7f75e1ed21bace22c00d3a07d81454"
lazy = true

    [[brainflow.download]]
    sha256 = "07be438a9a01edf560a3ec6c8db6b4c9c6e6f65d08a3b44afe81459f57c06bbb"
    url = "https://github.com/brainflow-dev/brainflow/releases/download/5.14.0/compiled_libs.tar"
